controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    dudeman.vy = -100
})
let dudeman: Sprite = null
scene.setBackgroundColor(9)
dudeman = sprites.create(img`
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    ......fbd1111111f.......
    ......fdd1111111df......
    ......fddd111111df......
    ......fdddddd111df......
    ......fdddddd111df......
    ......fbddddddd1df......
    ......ffbbddbfd1df......
    .......fcbbdcfddbf......
    .......fffbddccffff.....
    .......ffffcfbbb1bcf....
    ......ffffffffcd1b1f....
    ...ffffffffff..fdfdf....
    .....ffffff.....f.f.....
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(dudeman, 100, 0)
tiles.setCurrentTilemap(tilemap`level2`)
dudeman.ay = 1000
scene.cameraFollowSprite(dudeman)
